plugins {
    id 'java-library'
    id 'io.github.jpersist.hibernate-persistence'
}

dependencies {
    jpa platform('org.hibernate.orm:hibernate-platform:6.6.56.Final')

    implementation 'org.hibernate.orm:hibernate-core'

    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen'
}

repositories {
    mavenCentral()
}
