changelog:
  exclude:
    labels:
      - duplicate
      - question
    authors: []
  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "🤖 Automated Dependency Cleanups"
      labels:
        - dependencies
      authors:
        - dependabot[bot] # Explicitly groups Dependabot-authored PRs here
    - title: "📦 Dependency Updates"
      labels:
        - dependencies
    - title: "🛠️ Build & Maintenance"
      labels:
        - chore
        - documentation
    - title: "📝 Other Changes"
      labels:
        - "*"
