plugins {
    id 'com.gradle.enterprise' version '3.13.4'
}

gradleEnterprise {
    if (System.getenv('CI') != null) {
        buildScan {
            publishAlways()
            termsOfServiceUrl = 'https://gradle.com/terms-of-service'
            termsOfServiceAgree = 'yes'
        }
    }
}

rootProject.name = 'jpersist'

include 'plugins:eclipse-persistence-gradle-plugin'
include 'plugins:hibernate-persistence-gradle-plugin'
include 'plugins:persistence-gradle-plugin'

include 'plugins:persistence-gradle-plugin-functional-test'
