[versions]
jakarta-persistence = "3.1.0"
hibernate = "7.4.11.Final"
spock = "2.3-groovy-4.0"
asm = "9.10.1"

[libraries]
jakarta-persistence-api = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "jakarta-persistence" }
hibernate-core = { group = "org.hibernate.orm", name = "hibernate-core", version.ref = "hibernate" }
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
