[versions]
jakarta-persistence = "3.1.0"
hibernate = "6.6.56.Final"

[libraries]
jakarta-persistence-api = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "jakarta-persistence" }
hibernate-core = { group = "org.hibernate.orm", name = "hibernate-core", version.ref = "hibernate" }
