plugins {
    id 'java-library'
    id 'io.github.jpersist.hibernate-persistence'
}

dependencies {
    annotationProcessor platform('org.hibernate.orm:hibernate-platform:6.6.56.Final')
    testAnnotationProcessor platform('org.hibernate.orm:hibernate-platform:6.6.56.Final')
    implementation platform('org.hibernate.orm:hibernate-platform:6.6.56.Final')
    implementation 'org.hibernate.orm:hibernate-core'
}

repositories {
    mavenCentral()
}
