plugins {
    id 'java-platform'
}

javaPlatform {
    allowDependencies()
}

dependencies {
    constraints {
        api project(':lint-persistence-api')
        api project(':lint-persistence-jakarta')
        api project(':lint-persistence-legacy')
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.javaPlatform

            pom {
                name = 'Lint Persistence BOM'
                description = 'Bill of Materials (BOM) for convenient dependency management of all Lint Persistence modules'
            }
        }
    }
}
