plugins {
    id 'java-library'
    id 'io.github.jpersist.eclipse-persistence'
}

dependencies {
    jpa platform('org.eclipse.persistence:org.eclipse.persistence.parent:4.0.9')

    implementation 'org.eclipse.persistence:org.eclipse.persistence.jpa'

    jarFile project(':common-persistence-module')
    jarFile project(':bookstore-persistence-module')
}

persistence {
    main {
        persistenceUnits {
            'bookstore-service-persistence-unit' {
                jarFile(project(':common-persistence-module')) { jarTask ->
                    "lib/${jarTask.archiveFileName.get()}"
                }

                jarFile(project(':bookstore-persistence-module')) { jarTask ->
                    "lib/${jarTask.archiveFileName.get()}"
                }

                properties {
                    property 'eclipselink.weaving', 'static'
                }
            }
        }
    }
}
