plugins {
    id 'java-library'
    id 'io.github.jpersist.jpa'
}

dependencies {
    compileOnly libs.jakarta.persistence.api

    jarFile project(':common-persistence-module')
    jarFile project(':bookstore-persistence-module')
}

persistence {
    main {
        persistenceUnits {
            'bookstore-service-persistence-unit' {
                jarFile(project(':common-persistence-module')) { jarTask ->
                    "lib/${jarTask.archiveFileName.get()}"
                }

                jarFile(project(':bookstore-persistence-module')) { jarTask ->
                    "lib/${jarTask.archiveFileName.get()}"
                }
            }
        }
    }
}
