plugins {
    id "java-library"
}

dependencies {
    implementation project(':lint-persistence-api')
    compileOnly libs.hibernate.orm.core

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
